### PR TITLE
Add asynchronous methods

### PR DESCRIPTION
**Pull request by yak1ex**
Using AnyEvent::HTTP inside made LWP::UserAgent event-based friendly. However, $cv->recv without callback made blocking wait. Therefore, In AnyEvent without Coro, this will make recursive blocking wait error in most cases. One solution is to return condition variable and delegate choice how to wait results to users. On the other hand, this module intended to be interface-compatible with LWP::UserAgent. So, I added some _async methods whose parameters identical to originals, which means methods without _async suffix, but return value becomes condition variable. It will make this module more friendly to plain AnyEvent without Coro,

### CODE REVIEW

**Comment by tadam** [comment]
Thank you!
I'll check it out on weekend.

**Comment by yak1ex** [comment]
I would be glad if you could accept it.

I forgot to mention these codes based on other codes. simple_request_async is based on your code with little modification. Other _async methods are based on original LWP::UserAgent code with little modification. The other methods added by me are thin wrappers to call recv.

**Comment by yak1ex** [comment]
Sorry for repeated comments. I found a typo causing an error. So, I fixed it on the commit 29ed2f1.

**Comment by berekuk** [comment]
@yak1ex, can you add some tests for your patch?

**Comment by yak1ex** [comment]
I added tests as async.t based on callbacks.t

**Comment by tadam** [comment]
Sorry for the late response.
I tried to find a way to avoid copy-paste from LWP::UserAgent, but unfortunately the code structure of LWP::UserAgent doesn't allow to do it.
Code is merged and new version 0.08 is uploaded to CPAN.

P. S. I didn't check your code very carefully since it looks like you understand what you are doing.

**Pull request closed without merging**
