### PR TITLE
Add minimum support for request content by code reference, response content by filename or code reference

### PR DESCRIPTION
**Pull request by yak1ex**
Hi.

Now, I'm trying to make Net::Amazon::S3 AnyEvent-friendly by using this module. The tests of Net::Amazon::S3 depends on LWP::UserAgent behavior more than ones emulated by this module. So, I implemented the following features and corresponding tests.
- Request content specified by code reference
  
  NOTE: Actually, LWP::UserAgent uses chunked encoding in this case. It is, however, necessary to modify AnyEvent::HTTP itself. So, minimum support is added right now. Repeated calls of callback are made beforehand, and the results are collected and passed together.
- Response content specified by code reference
- Response content specified by filename

### CODE REVIEW

**Comment by berekuk** [comment]
I think this is great.
I wonder if it would be possible to partially reuse original LWP tests for this...

**Comment by yak1ex** [comment]
Thanks. It is a proper way to test emulated behavior. I'll check it.

**Comment by yak1ex** [comment]
Unfortunately, original LWP does not seem to have corresponding tests.
I added environment variable option USE_LWP for the following tests.
- request_content_ref.t
- response_content_cb.t
- response_content_file.t

If USE_LWP is defined, these tests use original LWP::UserAgent instead of this module. So, we can check if the results are identical between original and this module. By this test option, I could recognize different behavior of LWP::UserAgent whether Content-Length is specified or not. It was documented in POD section: LIMITATIONS AND DETAILS.

A note for "Do not call `response_data' callback when content is empty"; this follows original LWP::Protocol behavior.

**Comment by berekuk** [comment]
@tadam, since it seems like neither you nor I have time to review these patches, I propose we give @yak1ex a commit bit. And maybe PAUSE co-maint grants too.

**Comment by tadam** [comment]
Good idea. Done.
@yak1ex, feel free to merge your commits into original repo and upload it to CPAN. I hope it's acceptable for you.

**Comment by yak1ex** [comment]
Thank you. I'll try it in this weekend.

**Pull request merged**
